# site settings
title: Recoded
subtitle: by NOVATalks
email: youremailaddress@gmail.com
description: A series of talks and workshops by NOVATalks.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: Portugal
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url: https://www.facebook.com/novatalks.fct
github_url: https://github.com/novatalks/recoded.github.io
gitlab_url:
googleplus_url: 
instagram_url: https://www.instagram.com/novatalks.fct/
linkedin_url: https://www.linkedin.com/company/novatalks/about/
pinterest_url:
slack_url:
twitter_url: 
webpage_url: https://novatalks.github.io/
# build settings
markdown: kramdown

sass:
  style: compressed

